## 1. np.sort

Return a sorted copy of an array

numpy.sort(a, axis=-1, kind=None, order=None, *, stable=None)

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [2]:
np.sort(a)

array([ 9, 21, 24, 24, 26, 28, 47, 53, 61, 64, 64, 74, 92, 93, 94])

In [6]:
np.sort(a)[::-1]

array([94, 93, 92, 74, 64, 64, 61, 53, 47, 28, 26, 24, 24, 21,  9])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[89, 28, 46, 67],
       [28, 44, 91, 75],
       [82, 48, 94, 16],
       [61, 91, 68, 65],
       [53, 87, 60,  6],
       [89, 93, 48, 36]])

In [4]:
np.sort(b)

array([[28, 46, 67, 89],
       [28, 44, 75, 91],
       [16, 48, 82, 94],
       [61, 65, 68, 91],
       [ 6, 53, 60, 87],
       [36, 48, 89, 93]])

In [5]:
np.sort(b,axis = 0)

array([[28, 28, 46,  6],
       [53, 44, 48, 16],
       [61, 48, 60, 36],
       [82, 87, 68, 65],
       [89, 91, 91, 67],
       [89, 93, 94, 75]])

## 2. np.append

The numpy.append() appends values along the mentioned axis at the end of the array.

In [7]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [8]:
np.append(a,200)

array([ 93,  94,  24,  28,  61,  53,  64,  26,   9,  74,  21,  24,  64,
        92,  47, 200])

In [17]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[89., 28., 46., 67.,  1.],
       [28., 44., 91., 75.,  1.],
       [82., 48., 94., 16.,  1.],
       [61., 91., 68., 65.,  1.],
       [53., 87., 60.,  6.,  1.],
       [89., 93., 48., 36.,  1.]])

## 3. np.concatenate
numpy.concatenate() function concentanate a sequence of arrays along an existing axis.

In [19]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

np.concatenate((c,d))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## 4. np.unique
with the help og np.unique() method,we can get the unique values from an array given as parameter in np.unique() method.

In [23]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

np.unique(e)
print(np.unique(f))

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]
[1 2 3]


## 5. np.expand_dims
with the help of Numpy.expand_dims() method. we can get the expanded dimensions of an array.

In [24]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [25]:
np.expand_dims(a,axis = 0)

array([[93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47]])

In [26]:
np.expand_dims(a,axis = 1)

array([[93],
       [94],
       [24],
       [28],
       [61],
       [53],
       [64],
       [26],
       [ 9],
       [74],
       [21],
       [24],
       [64],
       [92],
       [47]])

## 6. np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [27]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [28]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 0,  1,  4,  5,  6,  9, 12, 13], dtype=int64),)

In [29]:
# replace all values > 50 with 0
np.where(a > 50,0,a)

array([ 0,  0, 24, 28,  0,  0,  0, 26,  9,  0, 21, 24,  0,  0, 47])

In [30]:
# replace all even numbers with 0
np.where(a % 2 == 0 , 0, a)

array([93,  0,  0,  0, 61, 53,  0,  0,  9,  0, 21,  0,  0,  0, 47])

## 7. np.argmax
The numpy.argmax() function return indices of the max element of the array in a particular axis

In [31]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [32]:
np.argmax(a)

1

In [33]:
b

array([[89, 28, 46, 67],
       [28, 44, 91, 75],
       [82, 48, 94, 16],
       [61, 91, 68, 65],
       [53, 87, 60,  6],
       [89, 93, 48, 36]])

In [34]:
np.argmax(b)

10

In [35]:
np.argmax(b,axis=0)

array([0, 5, 2, 1], dtype=int64)

In [36]:
np.argmax(b,axis=1)

array([0, 2, 2, 1, 1, 1], dtype=int64)

## 8. np.argmin
The numpy.argmin() function return indices of the min element of the array in a particular axis

In [37]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [38]:
np.argmin(a)

8

In [39]:
b

array([[89, 28, 46, 67],
       [28, 44, 91, 75],
       [82, 48, 94, 16],
       [61, 91, 68, 65],
       [53, 87, 60,  6],
       [89, 93, 48, 36]])

In [40]:
np.argmin(b,axis=1)

array([1, 0, 3, 0, 3, 3], dtype=int64)

## 9. np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [41]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [42]:
np.cumsum(a)

array([ 93, 187, 211, 239, 300, 353, 417, 443, 452, 526, 547, 571, 635,
       727, 774])

In [43]:
b

array([[89, 28, 46, 67],
       [28, 44, 91, 75],
       [82, 48, 94, 16],
       [61, 91, 68, 65],
       [53, 87, 60,  6],
       [89, 93, 48, 36]])

In [49]:
# column wise
np.cumsum(b,axis=0)

array([[ 89,  28,  46,  67],
       [117,  72, 137, 142],
       [199, 120, 231, 158],
       [260, 211, 299, 223],
       [313, 298, 359, 229],
       [402, 391, 407, 265]])

In [48]:
# row wise
np.cumsum(b,axis=1)

array([[ 89, 117, 163, 230],
       [ 28,  72, 163, 238],
       [ 82, 130, 224, 240],
       [ 61, 152, 220, 285],
       [ 53, 140, 200, 206],
       [ 89, 182, 230, 266]])

## 10. np.cumprod
numpy.cuprodm() function is used when we want toproductm of array elements over a given axis.

In [45]:
np.cumprod(a)

array([         93,        8742,      209808,     5874624,   358352064,
        1812790208,    54456320,  1415864320,  -142123008, -1927168000,
       -1815822336,  -630063104, -1669332992,  1040187392,  1644167168])

In [50]:
np.cumprod(b,axis=0)

array([[         89,          28,          46,          67],
       [       2492,        1232,        4186,        5025],
       [     204344,       59136,      393484,       80400],
       [   12464984,     5381376,    26756912,     5226000],
       [  660644152,   468179712,  1605414720,    31356000],
       [-1332212616,   591040256,  -249504768,  1128816000]])

In [51]:
np.cumprod(b,axis=1)

array([[      89,     2492,   114632,  7680344],
       [      28,     1232,   112112,  8408400],
       [      82,     3936,   369984,  5919744],
       [      61,     5551,   377468, 24535420],
       [      53,     4611,   276660,  1659960],
       [      89,     8277,   397296, 14302656]])

## 11. np.percentile
numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [52]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [53]:
np.percentile(a,100)

94.0

In [54]:
np.percentile(a,0)

9.0

In [55]:
np.percentile(a,50)

53.0

## 12. np.histogram
Numpy has a built in numpy.histogram() function which represent the frequency of data distribution in the graphical form

In [56]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [59]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 0, 5, 0, 1, 1, 3, 1, 0, 3], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## 13. np.corrcoef
Return pearson product-moment correlation coefficients

In [61]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## 14. np.isin
with the help of numpy.isin() method we can see that one array having values are checked in a different numpy array having different elements with different size.

In [62]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [65]:
items = [93,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([93])

## 15. np.flip
The numpy.flip() function reverses the order of array elements alongs the specified axis preserving the shape of the array.

In [66]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [67]:
np.flip(a)

array([47, 92, 64, 24, 21, 74,  9, 26, 64, 53, 61, 28, 24, 94, 93])

In [70]:
b

array([[89, 28, 46, 67],
       [28, 44, 91, 75],
       [82, 48, 94, 16],
       [61, 91, 68, 65],
       [53, 87, 60,  6],
       [89, 93, 48, 36]])

In [71]:
np.flip(b)

array([[36, 48, 93, 89],
       [ 6, 60, 87, 53],
       [65, 68, 91, 61],
       [16, 94, 48, 82],
       [75, 91, 44, 28],
       [67, 46, 28, 89]])

## 16. np.put
The numpy.put() function replace specific elements of an array with given values of p_array.Array indexed works on flattened array.

In [72]:
a

array([93, 94, 24, 28, 61, 53, 64, 26,  9, 74, 21, 24, 64, 92, 47])

In [74]:
np.put(a,[0,1],[930,940])
a

array([930, 940,  24,  28,  61,  53,  64,  26,   9,  74,  21,  24,  64,
        92,  47])

## 17. np.delete
The numpy.delete() function returns a new array with the deletion of sun-array along with the mentioned axis.

In [75]:
a

array([930, 940,  24,  28,  61,  53,  64,  26,   9,  74,  21,  24,  64,
        92,  47])

In [76]:
np.delete(a,0)

array([940,  24,  28,  61,  53,  64,  26,   9,  74,  21,  24,  64,  92,
        47])

In [77]:
np.delete(a,[0,2,3])

array([940,  61,  53,  64,  26,   9,  74,  21,  24,  64,  92,  47])

## 17. Set function
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [79]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])

np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7])

In [80]:
np.intersect1d(a,b)

array([3, 4, 5])

In [83]:
np.setdiff1d(a,b)

array([1, 2])

In [84]:
np.setdiff1d(b,a)

array([6, 7])

In [85]:
np.setxor1d(a,b)

array([1, 2, 6, 7])

In [86]:
np.in1d(a,1)

array([ True, False, False, False, False])

## 18. np.clip
numpy.clip() function is used to clip (limit) the values in an array

In [88]:
a = np.random.randint(1,100,15)
a

array([98, 36, 91, 76, 65, 96, 19, 98, 50, 97, 32, 88, 60, 57, 36])

In [89]:
np.clip(a,a_min = 25,a_max = 75)

array([75, 36, 75, 75, 65, 75, 25, 75, 50, 75, 32, 75, 60, 57, 36])

## 19. np.swapaxes
np.swapaxes is a function in NumPy used to swap two axes (dimensions) of an array. It is useful for reshaping and manipulating multi-dimensional arrays.

In [92]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

swapped = np.swapaxes(arr, 0, 1)
print(swapped)

[[1 4]
 [2 5]
 [3 6]]


## 20. np.uniform 
np.uniform is a function in NumPy that generates random numbers from a uniform distribution within a specified range.

In [93]:
 # Generates a random number between 0 and 10
random_number = np.random.uniform(0, 10) 
print(random_number)

2.1077169779940363


In [95]:
# 3x3 array with values between 5 and 15
random_array = np.random.uniform(5, 15, size=(3, 3))
print(random_array)

[[14.34362504  8.07364583  6.92965734]
 [ 6.17302795  8.53042391  6.17577143]
 [ 6.03765242  8.11232771  8.65629113]]


## 21.np.count_nonzero
np.count_nonzero is a NumPy function used to count the number of nonzero elements in an array.

In [96]:
arr = np.array([0, 1, 2, 0, 3, 4, 0])
count = np.count_nonzero(arr)
print(count)

4


In [97]:
arr2d = np.array([[0, 2, 0], 
                  [3, 0, 4]])

count_all = np.count_nonzero(arr2d)  # Counts in the entire array
count_axis0 = np.count_nonzero(arr2d, axis=0)  # Counts along columns
count_axis1 = np.count_nonzero(arr2d, axis=1)  # Counts along rows

print("Total nonzero:", count_all)
print("Nonzero count per column:", count_axis0)
print("Nonzero count per row:", count_axis1)

Total nonzero: 3
Nonzero count per column: [1 1 1]
Nonzero count per row: [1 2]


## 22. np.tile
np.tile is a NumPy function used to repeat an array along specified dimensions.

In [98]:
arr = np.array([1, 2, 3])
tiled_arr = np.tile(arr, 3)  # Repeat the array 3 times
print(tiled_arr)

[1 2 3 1 2 3 1 2 3]


In [99]:
arr2d = np.array([[1, 2], 
                  [3, 4]])

tiled_arr2d = np.tile(arr2d, (2, 3))  # Repeat 2 times along rows, 3 times along columns
print(tiled_arr2d)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


## 23. np.repeat
np.repeat is a NumPy function used to repeat elements within an array along a specified axis.

In [100]:
arr = np.array([1, 2, 3])
repeated_arr = np.repeat(arr, 3)  # Each element is repeated 3 times
print(repeated_arr)

[1 1 1 2 2 2 3 3 3]


In [101]:
arr2d = np.array([[1, 2], 
                  [3, 4]])

repeated_rows = np.repeat(arr2d, 2, axis=0)  # Repeat rows
repeated_cols = np.repeat(arr2d, 2, axis=1)  # Repeat columns

print("Repeated Rows:\n", repeated_rows)
print("Repeated Columns:\n", repeated_cols)

Repeated Rows:
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
Repeated Columns:
 [[1 1 2 2]
 [3 3 4 4]]
