## NUMPY
NumPy, which stands for Numerical Python, is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures

- Numpy is a Linear Algebra Library in Python and it is the holy grail and the main building block of data science.
- Numpy stands for Numerical python which is used to perform numerical calculations.
- Numpy is used to handle arrays and matrices.

## What is Numpy?

- Numpy in python is a library that used to work with arrays.
- It is also a datastructure used to store multiple values.
- Numpy provides efficient way of storing and manipulating data.
- It offers wide variety of mathematical functions which helps in solving complex math problems of linear algebra fourier transform and vectors.

## Why Numpy?

- Faster and more compact then list.
- Consume less memory.
- data type can be specified.
- High level mathematical functions can be used.
- used to solve problems related to linear algebra fourier transfomr,vector etc.

## What is an array?
- Numpy array commonly used data strucures in python that store data as a grid or a matrix and easy to access.

## Numpy Array vs python sequence
- Numpy arrays have a fixed size at creation, unlike pyhton lists (which can grow dynamically). changing the size of an ndarray will create a new array and delete the orginal.
- The elements in a Numpy array are all required to be of the same data type, and thus will be the same size in memory.
- NUmpy array facilitate advanced mathematical and other type of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using python's built in sequences.

### Import Numpy Package

In [1]:
import numpy as np

### Create Numpy Array

In [2]:
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


### Create numpy array to store values

In [3]:
arr1 = np.array([6,7,8,9,4,5,6])
print(arr1)
print(type(arr1))

[6 7 8 9 4 5 6]
<class 'numpy.ndarray'>


In [4]:
colors = np.array(("Blue","Green","Orange","Yellow","White"))
print(colors)
print(type(colors))

['Blue' 'Green' 'Orange' 'Yellow' 'White']
<class 'numpy.ndarray'>


In [5]:
# 2D array
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [6]:
# 3D array
arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
arr1 = np.array([1,2,3,4,5],dtype = 'float')
print(arr1)

[1. 2. 3. 4. 5.]


### How to create an array using list

In [8]:
List = [34,56,78,98,76,56,45,34,23]
arr3 = np.array(List)
print(arr3)
print(type(arr3))

[34 56 78 98 76 56 45 34 23]
<class 'numpy.ndarray'>


### How to create an array using Tuple

In [9]:
Tuple = (101,102,103,104,105,106,107,108)
arr4 = np.array(Tuple)
print(arr4)
print(type(arr4))

[101 102 103 104 105 106 107 108]
<class 'numpy.ndarray'>


### 1-D Array Vector

In [10]:
arr5 = np.array([1,2,3,4,5,6])
print(arr5)
print(type(arr5))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


## Functionality in Numpy array

### 1. Dimension of Array

In [11]:
print(arr5)
print("Diamention of array is: ",arr5.ndim)

[1 2 3 4 5 6]
Diamention of array is:  1


### 2. Number of elements

In [12]:
print(arr5)
print("Number of elements is: ",arr5.size)

[1 2 3 4 5 6]
Number of elements is:  6


### 3. DataTypes of elements

In [13]:
print(arr5)
print("Datatype of elements of array: ",arr5.dtype)

[1 2 3 4 5 6]
Datatype of elements of array:  int32


### 4. Datatypes of Array

In [14]:
print(arr5)
print("Datatype of array: ",type(arr5))

[1 2 3 4 5 6]
Datatype of array:  <class 'numpy.ndarray'>


### 5. Check type of shape

In [15]:
print(arr5)
print("Shape of array: ",arr5.shape)

[1 2 3 4 5 6]
Shape of array:  (6,)


### 6. Check memory occupy

In [16]:
print(arr5)
print("Memory occupy",arr5.itemsize)

[1 2 3 4 5 6]
Memory occupy 4


### 2-D Matrices

In [17]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
arr6 = np.array([[4,5,6,7],[8,9,1,2],[3,2,4,3],[9,2,1,4]])
print(arr6)

[[4 5 6 7]
 [8 9 1 2]
 [3 2 4 3]
 [9 2 1 4]]


In [19]:
print("Dimension of the array:",arr6.ndim)

Dimension of the array: 2


In [20]:
print("shape of the array: ",arr6.shape)

shape of the array:  (4, 4)


In [21]:
print("Number of elements in array: ",arr6.size)

Number of elements in array:  16


In [22]:
print("Datatype of elements: ",arr6.dtype)

Datatype of elements:  int32


In [23]:
print("Datatype of array: ",type(arr6))

Datatype of array:  <class 'numpy.ndarray'>


### 3-D Array Tensors

In [24]:
arr7 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr7)
print(type(arr7))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [25]:
print("Dimension of array: ",arr7.ndim)

Dimension of array:  3


In [26]:
print("Number of elements in array: ",arr7.size)

Number of elements in array:  9


In [27]:
print("shape of array: ",arr7.shape)

shape of array:  (1, 3, 3)


In [28]:
print("Datatype of elements: ",arr7.dtype)

Datatype of elements:  int32


In [29]:
print("Datatype of array: ",type(arr7))

Datatype of array:  <class 'numpy.ndarray'>


## Built-In Function 

### 1. arange :- 
- It is used to generate evenly spaced values within a given interval.

In [30]:
# Generate values from 0 to 14
np.arange(15) # end value is not included

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
# Generate values from 0 to 30
np.arange(31)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
# Generate values from 101 to 150
np.arange(101,151)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [33]:
# Generate values from 400 to 480
np.arange(400,481)

array([400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
       439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
       452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
       465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
       478, 479, 480])

In [34]:
# Generate frist 10 even number
np.arange(0,21,2) # arange(start,stop,step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
# Generate an array which includes 10 multiple of 5
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [36]:
# Generate an array which includes 10 multiple of 8
np.arange(8,81,8)

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

### Reshape
In NumPy, the reshape() function is used to change the shape of an array without modifying its data. 

In [38]:
# reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 2. Ones:-
- It returns an array with all one

In [39]:
# return 1-D array with all one
np.ones(3)

array([1., 1., 1.])

In [40]:
# return 1-D array with 10 elements as 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
# create unit matrix of order (2,2)
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [42]:
# create unit matrix off oredr (5,3)
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### 3. Zeros
- It returns an array with all zeros

In [43]:
# create an 1-D array with 5 elements as 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
# create an 2-D array or order (3,3)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# create an 2-D array or order (5,5)
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 4. eye :-
- create and identity matrix

In [46]:
# create (2,2) identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [47]:
# create (3,3) identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# create (4,3) identity matrix
np.eye(4,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

### 5. Full:-
- It is used generate array with same elements

In [49]:
# create an 2-D array with all elements as 10
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [50]:
# Create (4,3) matrix with all elements as 20
np.full((4,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

### 6. Linspace:-
- It is used to generate linearly spaced values

In [51]:
# Generate linearly space values between 1 to 5
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [52]:
# generate 10 equally spaced values between 1 to 100
np.linspace(1,100,num=10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [53]:
# generate 10 numbers between 1 to 1000 and find the difference
np.linspace(1,1000,num=10,retstep=True)

(array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.]),
 111.0)

## Random

### 1. randint:-
- It is used to generate random integers for given interval

In [54]:
# create an array which includes 10 random integers between 1 to 100
np.random.randint(1,100,10)

array([96, 48, 33, 90, 11, 98, 83, 41, 50, 71])

In [55]:
# create an array which includes 5 random integers between 1 to 1000
np.random.randint(1,1000,5)

array([ 36, 269, 968, 241, 340])

In [56]:
# create 2-D array of order (2,2) which includes random integers between 20 to 60
np.random.randint(20,60,size=(2,2))

array([[40, 35],
       [44, 39]])

In [57]:
# create 2-D array of order (2,3) which includes random integers between 2 to 200
np.random.randint(2,200,size=(2,3))

array([[170,  54,   9],
       [109, 140,  32]])

### 2. rand:-
- It generates random values between the range [0,1]

In [58]:
# generate 10 random numbers between 0 to 1
np.random.rand(10)

array([0.59365066, 0.3601074 , 0.70054291, 0.55756034, 0.58341455,
       0.94346501, 0.27591362, 0.77552622, 0.55174152, 0.39802381])

In [59]:
# generate 100 random numbers between 0 to 1
np.random.rand(100)

array([0.74839201, 0.40727485, 0.29272873, 0.48786353, 0.98199191,
       0.16517616, 0.52796956, 0.9412643 , 0.09210126, 0.24034458,
       0.24409006, 0.99317515, 0.42811943, 0.41699452, 0.55367439,
       0.58229803, 0.82016413, 0.48558568, 0.16897557, 0.00531727,
       0.80214065, 0.96349826, 0.96543716, 0.00888816, 0.53638252,
       0.69881724, 0.35607207, 0.73707816, 0.90713263, 0.28963665,
       0.8303174 , 0.95964739, 0.95148478, 0.18726668, 0.76858245,
       0.27438457, 0.78010644, 0.36072447, 0.22647559, 0.09785707,
       0.23369014, 0.69286958, 0.48390772, 0.18788586, 0.55952149,
       0.00604904, 0.6770239 , 0.28682164, 0.50648621, 0.62951138,
       0.92135955, 0.66791264, 0.5021459 , 0.58222396, 0.97055398,
       0.77818829, 0.48547015, 0.58335241, 0.55129374, 0.92826917,
       0.95379118, 0.76947025, 0.98379914, 0.30667238, 0.12914035,
       0.24967159, 0.89523601, 0.74075758, 0.65945531, 0.73385098,
       0.17127919, 0.789841  , 0.37067779, 0.84717864, 0.04451

In [60]:
# create 2-D array of order (4,4) with random numbers between 0 to 1
np.random.rand(4,4)

array([[0.22095886, 0.58048038, 0.41021048, 0.49828911],
       [0.08012615, 0.86878468, 0.04315458, 0.20898678],
       [0.90303247, 0.33593541, 0.45013533, 0.08666064],
       [0.44841798, 0.77286654, 0.36030597, 0.33396195]])

In [61]:
# create matrix of order (7,3) which includes
np.random.rand(7,3)

array([[0.33659009, 0.99952692, 0.93333408],
       [0.2475255 , 0.29411181, 0.9774275 ],
       [0.29843574, 0.92598844, 0.71292709],
       [0.011664  , 0.09806121, 0.03117669],
       [0.89570577, 0.90487542, 0.61855064],
       [0.96311786, 0.53122236, 0.06457554],
       [0.16446325, 0.09124349, 0.71073395]])

### 3. randn
- It is used to generate random numbers from normal distribution within a range [-3,3]

In [62]:
# generate 10 random numbers from normal distributuon
np.random.randn(10)

array([-1.91966609, -0.55261325,  0.04447149,  0.7780141 ,  2.56856894,
       -0.33054469, -1.2336896 ,  0.45111653, -1.59829292, -1.23180777])

In [63]:
# create 2-D array of order (5,5) which includes normal distribution values
np.random.randn(5,5)

array([[ 1.06137161,  0.38621964, -0.87461917, -0.38139117, -0.27328853],
       [-0.37493901, -0.0737769 , -2.13264554, -1.81340573, -1.30913504],
       [ 0.27521232, -0.53514085, -0.23288824,  0.44498531, -0.4240127 ],
       [-0.65138322,  1.25319375, -0.57129015, -1.73182208, -1.4263522 ],
       [ 0.29839341,  0.74785277,  0.57577934,  0.8339807 ,  1.67673382]])

In [64]:
# create 10 random integers between 1 to 10000
rand_num = np.random.randint(1,10000,10)
print(rand_num)

[5391 8663 4109 5368 2022 4470 9619 1047 7045 6668]


In [65]:
# maximum value
np.max(rand_num)

9619

In [66]:
# index position of maximum value
np.argmax(rand_num)

6

In [67]:
# minimum value
np.min(rand_num)

1047

In [68]:
# index position of minimum value
np.argmin(rand_num)

7

## Indexing

In [69]:
A = np.arange(20,30)
print(A)

[20 21 22 23 24 25 26 27 28 29]


In [70]:
# fetch 23
A[3]

23

In [71]:
# fetch 23,24,25
A[3:6]

array([23, 24, 25])

In [72]:
# how to reverse array
A[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

### Indexing with 2-D array

In [73]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [74]:
# fetch 1st row
B[[0]]

array([[1, 2, 3]])

In [75]:
# fetch 2nd row
B[[1]]

array([[4, 5, 6]])

In [76]:
# fetch 3rd row
B[[2]]

array([[7, 8, 9]])

In [77]:
# fetch 1st and 2nd row
B[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
# fetch 1st and 3rd row
B[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [79]:
# fetch 4
B[1][0]

4

In [80]:
# fetch 9
B[2][2]

9

In [81]:
# fetch 6
B[1,2]

6

In [82]:
# fetch first column
B[:,[0]]

array([[1],
       [4],
       [7]])

In [83]:
# fetch second column
B[:,[1]]

array([[2],
       [5],
       [8]])

In [84]:
# fetch third column
B[:,[2]]

array([[3],
       [6],
       [9]])

In [85]:
# fetch 1st and 3rd column
B[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [86]:
# fetch 1st and 2nd column
B[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [87]:
B[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [88]:
B[1:3,[0]]

array([[4],
       [7]])

In [89]:
B[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [90]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
# fetch 1st row
a1[[0]]

array([[0, 1, 2, 3]])

In [92]:
# fetch 2nd row
a1[[1]]

array([[4, 5, 6, 7]])

In [93]:
# fetch first column
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
a1[:,[0]]

array([[0],
       [4],
       [8]])

In [95]:
a1[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [96]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
a1[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [98]:
a1[1:,1::2]

array([[ 5,  7],
       [ 9, 11]])

In [99]:
a2 = np.arange(27).reshape(3,3,3)
a2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [100]:
a2[[1]]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [101]:
a2[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
a2[0][1]

array([3, 4, 5])

In [103]:
a2[1][2,1]

16

In [104]:
a2[2][1:,1:]

array([[22, 23],
       [25, 26]])

In [105]:
a2[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

## Array Operations

In [106]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([2,4,6,8,10])

#### Arithmatic

In [107]:
# Addition
arr1+arr2

array([12, 24, 36, 48, 60])

In [108]:
# Subtraction
arr1-arr2

array([ 8, 16, 24, 32, 40])

In [109]:
# Multiplication
arr1*arr2

array([ 20,  80, 180, 320, 500])

In [110]:
# Division
arr1/arr2

array([5., 5., 5., 5., 5.])

In [109]:
# scaler operation
arr1+5

array([15, 25, 35, 45, 55])

#### Relational

In [110]:
arr1 > 5

array([ True,  True,  True,  True,  True])

In [111]:
arr1 < 25

array([ True,  True, False, False, False])

In [112]:
arr1 == 15

array([False, False, False, False, False])

## Array Function

In [113]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[49., 83., 89.],
       [47., 34., 12.],
       [32., 84., 33.]])

### Maximum
Find the largest value in an array.

In [114]:
np.max(a1)

89.0

In [115]:
np.max(a1,axis = 1 )

array([89., 47., 84.])

### Minimum
Find the smallest value in an array.

In [116]:
np.min(a1)

12.0

### sum
Calculate the sum of all elements in the array.

In [117]:
np.sum(a1)

463.0

### Product
Calculate the product of all elements in the array.

In [118]:
np.prod(a1)

615694684695552.0

### Mean 
Compute the average of the array elements.

In [119]:
np.mean(a1)

51.44444444444444

### Median
Find the median (middle value) of the array elements.

In [120]:
np.median(a1)

47.0

### Standard Deviation
Compute the standard deviation (square root of variance).

In [121]:
np.std(a1)

25.970543617769522

### Variance
Compute the variance (measure of spread) of the array.

In [122]:
np.var(a1)

674.4691358024692

### Dot Product
The dot product of two arrays (vectors or matrices).

In [123]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

### Logarithm
Compute logarithms (base 2, base 10, or natural log).

In [124]:
# log 
np.log(a1)

array([[3.8918203 , 4.41884061, 4.48863637],
       [3.8501476 , 3.52636052, 2.48490665],
       [3.4657359 , 4.4308168 , 3.49650756]])

### Exponential (exp)
Compute the exponential (e^x) of each element in the array.

In [125]:
# exponents
np.exp(a1)

array([[1.90734657e+21, 1.11286375e+36, 4.48961282e+38],
       [2.58131289e+20, 5.83461743e+14, 1.62754791e+05],
       [7.89629602e+13, 3.02507732e+36, 2.14643580e+14]])

### Round
Round elements to the nearest integer.

In [126]:
# round
np.round(np.random.random((2,3))*100)

array([[34., 48., 49.],
       [40., 88., 15.]])

### Floor (floor)
Round elements down to the nearest integer.

In [127]:
# floor
np.floor(np.random.random((2,3))*100)

array([[82., 88., 65.],
       [ 8., 40., 72.]])

### Ceil (ceil)
Round elements up to the nearest integer.

In [128]:
# ceil
np.ceil(np.random.random((2,3))*100)

array([[34., 82., 10.],
       [17., 39.,  3.]])

### Iteration on Array

In [130]:
a1

array([[49., 83., 89.],
       [47., 34., 12.],
       [32., 84., 33.]])

In [131]:
for i in a1:
    print(i)

[49. 83. 89.]
[47. 34. 12.]
[32. 84. 33.]


In [132]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [135]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Transpose
The transpose() function in NumPy is used to flip the dimensions of an array. For a 2D array, this swaps rows with columns.

In [136]:
# Transpose
np.transpose(a1)

array([[49., 47., 32.],
       [83., 34., 84.],
       [89., 12., 33.]])

In [137]:
a1.T

array([[49., 47., 32.],
       [83., 34., 84.],
       [89., 12., 33.]])

### Ravel
The ravel() function is used to flatten an array into a 1D array. 

In [138]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking 
#### 1. Horizontal(hstack)
Combines arrays along columns (axis 1).

In [139]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [140]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

#### 2.Vertical Stacking (vstack)
Combines arrays along rows (axis 0).

In [141]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Spliting

#### 1. Horizontal Splitting (hsplit)
Splits an array along its columns (axis 1).

In [142]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### vertical spliting (vsplit)
Splits an array along its rows (axis 0).

In [143]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]